/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vnpay.eth.api.client;

import java.util.*;
import org.json.JSONObject;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String fileName = "config.yml";
        Configuration cfg = Configuration.loadConfig(fileName);

        Api api = new Api(cfg);

        api.Init();

       JSONObject obj = api.Login();
       System.out.println("Res: " + obj);

        // JSONObject na = api.AccountNew();
        // System.out.println("Res: " + na);
    }
}
